export const ADD_NUMBER = 'ADD_NUMBER';
export const SUB_NUMBER = 'SUB_NUMBER';

export const LOGIN_WITH_TOKEN_INIT = 'LOGIN_WITH_TOKEN_INIT';
export const LOGIN_WITH_TOKEN_SUCCESS = 'LOGIN_WITH_TOKEN_SUCCESS';
export const LOGIN_WITH_TOKEN_FAILED = 'LOGIN_WITH_TOKEN_FAILED';
